version: "3.8"

services:
  coder-docker:
    image: codercom/code-server:latest
    container_name: coder-docker
    restart: unless-stopped
    user: "1000:1001"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/var/apps/coder-docker/target:/home/coder/.target:rw"  # target路径
      - "/vol1/1000/VscodeProject:/home/coder/project"  # 项目路径
    entrypoint: []
    command: ["/home/coder/.target/proxy/coder-proxy-linux-amd64"]
    network_mode: bridge
  